routes/admin.php
<?php

    Route::group(['prefix' => env('ADMIN_ROUTE'),'namespace'=>'App\\Http\\Controllers\\Admin','as' =>'admin.','middleware'=>['web','auth']], function () {
        Route::get('/', function(){
            // return redirect()->route('admin.users.index');
            return redirect()->route('admin.dashboard.index');
        });
        // Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');

        // Route::get('/dashboard','DashboardController')->name('admin.dashboard');
        Route::resource('/dashboard','DashboardController');
        Route::resource('/users','UserController');
        Route::resource('/roles','RoleController');
        Route::resource('/permissions','PermissionController');
    });
?>

routes/front.php
<?php

use Laravel\Socialite\Facades\Socialite;
    Route::group(['prefix' => '','namespace'=>'App\\Http\\Controllers\\','as' =>'front.','middleware'=>['web']], function () {
        Route::view('/','homepage');
        Route::get('/business/register','BusinessController@register')->name('business.register');
        Route::post('/business/register','BusinessController@Saveregister')->name('business.register.save');
        Route::post('/business/register/check-username', 'BusinessController@postCheckUsername')->name('business.postCheckUsername');
        Route::post('/business/register/check-email', 'BusinessController@postCheckEmail')->name('business.postCheckEmail');
    });

?>

routes/user.php
<?php
Route::group(['prefix' => env('USER_ROUTE'),'namespace'=>'App\\Http\\Controllers\\Agent','as' =>'agent.','middleware'=>['web','auth']], function () {
    Route::get('/',function(){
        return "User Prefix";
    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Front\PropertyController;

Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});

Auth::routes();

Route::get('oauth/{provider}', 'App\Http\Controllers\Auth\LoginController@redirectToProvider');
Route::get('oauth/{provider}/callback','App\Http\Controllers\Auth\LoginController@handleProviderCallback');

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/properties', [PropertyController::class, 'index'])->name('front.properties');

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;


use DB;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Validator;

class RoleController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    public function index(Request $request)
    {
        $user = User::where('id',Auth::id())->first();
        $roles = $user->getRoleNames();
        foreach($roles as $role){
            if($role==='Super-Admin'){
                $data['roles'] = Role::orderBy('id','asc')->paginate(5);
            } else {
                $data['roles'] = Role::where('slug','<>','super-admin')->orderBy('id','asc')->paginate(5);
            }
        }
        return view('admin.roles.index',$data)
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function create()
    {
		$permissions = Permission::all(); //Get all permissions
		$data['permissions'] = $permissions->groupBy('group');
        return view('admin.roles.create',$data);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:roles,name',
            'slug' => 'required|unique:roles,slug',
            'permission' => 'required',
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
        }
        $role = Role::create([
            'name' => $request->input('name'),
            'slug' => $request->input('slug'),
            'description' => $request->input('description')
        ]);
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('admin.roles.index')
                        ->with('toast_success','Role created successfully');
    }

    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();

        return view('admin.roles.show',compact('role','rolePermissions'));
    }

    public function edit($id)
    {
		$data['role'] = Role::findOrFail($id);
		$permissions = Permission::all();
		$data['permissions'] = $permissions->groupBy('group');
		$data['role_permission'] = $data['role']->permissions()->pluck('id','id')->toArray();
        return view('admin.roles.edit',$data);
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => "required|unique:roles,name,$id",
            'slug' => "required|unique:roles,slug,$id",
            'permission' => 'required',
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();
        }
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->slug = $request->input('slug');
        $role->description = $request->input('description');
        $role->save();
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('admin.roles.index')
                        ->with('toast_success','Role updated successfully');
    }

    public function destroy($id)
    {
        Role::where('id',$id)->delete();
        // DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('admin.roles.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.ace_layout')

@push('styles')

@endpush

@section('content')
    {{-- <div class="row justify-content-center">
        <div class="col-md-12"> --}}
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    {!! Form::open(['route' =>'admin.roles.store', 'method' => 'POST', 'class' => 'form-horizontal',
                    'id' => 'validation-form', "enctype" => "multipart/form-data"]) !!}
                        @include('admin.roles.form')
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Publish</button>
                            <a href="{{ route('admin.roles.index') }}" class="btn btn-warning">Back</a>
                        </div>
                    {!! Form::close() !!}
                </div>

            </div>
        {{-- </div>
    </div> --}}
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            $('table th input:checkbox').on('click' , function(){
                var that = this;
                $(this).closest('table').find('input:checkbox')
                    .each(function(){
                        this.checked = that.checked;
                        $(this).closest('tr').toggleClass('selected');
                    });
            });
            $('.group').on('click' , function(){
                var that = this;
                $(this).closest('tr').find('input:checkbox')
                    .each(function(){
                        this.checked = that.checked;
                        $(this).closest('tr').toggleClass('selected');
                    });
            });
        });
    </script>

    <script>
        $(document).ready(function(){
            $('#name').keyup(function(e){
                var str = $('#name').val();
                str = str.replace(/\W+(?!$)/g, '-').toLowerCase();//rplace stapces with dash
                $('#slug').val(str);
                $('#slug').attr('placeholder', str);
            });
        });
    </script>
@endpush

resources/views/admin/roles/edit.blade.php
@extends('layouts.ace_layout')

@push('styles')

@endpush

@section('content')
    {{-- <div class="row justify-content-center">
        <div class="col-md-12"> --}}
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
					{!! Form::model($role, ['route' => ['admin.roles.update', $role->id], 'method' => 'POST', 'class' => 'form-horizontal',
					'id' => 'validation-form', "enctype" => "multipart/form-data"]) !!}
						{{method_field('PUT')}}
						{!! Form::hidden('id', $role->id) !!}
                        @include('admin.roles.form')
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Publish</button>
                            <a href="{{ route('admin.roles.index') }}" class="btn btn-warning">Back</a>
                        </div>
                    {!! Form::close() !!}
                </div>

            </div>
        {{-- </div>
    </div> --}}
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            $('table th input:checkbox').on('click' , function(){
                var that = this;
                $(this).closest('table').find('input:checkbox')
                    .each(function(){
                        this.checked = that.checked;
                        $(this).closest('tr').toggleClass('selected');
                    });
            });
            $('.group').on('click' , function(){
                var that = this;
                $(this).closest('tr').find('input:checkbox')
                    .each(function(){
                        this.checked = that.checked;
                        $(this).closest('tr').toggleClass('selected');
                    });
            });
        });
    </script>

    <script>
        $(document).ready(function(){
            $('#name').keyup(function(e){
                var str = $('#name').val();
                str = str.replace(/\W+(?!$)/g, '-').toLowerCase();//rplace stapces with dash
                $('#slug').val(str);
                $('#slug').attr('placeholder', str);
            });
        });
    </script>
@endpush

resources/views/admin/roles/form.blade.php
<div class="form-group">
    <div class="row">
        {!! Form::label('name', 'Role Name', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-5">
            {!! Form::text('name', null, ["placeholder" => "", "class" => "form-control border-form",  "required"]) !!}
        </div>

        {!! Form::label('slug', 'Slug', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-5">
            {!! Form::text('slug', null, ["placeholder" => "", "class" => "form-control border-form", "required"]) !!}
        </div>
    </div>
</div>

<div class="form-group">
    <div class="row">
        {!! Form::label('description', 'Description', ['class' => 'col-sm-2 control-label']) !!}
        <div class="col-sm-12">
            {!! Form::textarea('description', null, ["placeholder" => "", "class" => "form-control border-form","rows"=>"2"]) !!}
        </div>
    </div>
</div>

<div class="form-group">
    {!! Form::label('permission', 'Permissions', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-12">
            <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th width="20%">Group</th>
                    <th class="center">
                        <label class="pos-rel">
                            <input type="checkbox" class="ace" />
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th>Access</th>
                </tr>
                </thead>
                <tbody>
                @if($permissions && $permissions->count())
                    @foreach($permissions as $key => $permission)
                        <tr>
                            <td><strong>{{$permission->first()->group}}</strong></td>
                            <td class="center first-child">
                                <label>
                                    <input type="checkbox" name="chkIds[]" value="{{ $key }}" class="ace group" />
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td>
                                @foreach($permission as $access)
                                    <label>
                                        @if (!isset($role_permission))
                                            {!! Form::checkbox('permission[]', $access->id, false, ['class' => 'ace']) !!}
                                        @else
                                            {!! Form::checkbox('permission[]', $access->id, array_key_exists($access->id, $role_permission), ['class' => 'ace']) !!}
                                        @endif
                                        <span class="lbl"> {{ $access->slug}} </span>
                                    </label>
                                @endforeach
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr><td colspan="7">No data found.</td></tr>
                @endif
                </tbody>
            </table>
        <div class="control-group">
        </div>
    </div>
</div>

resources/views/admin/roles/index.blade.php
@extends('layouts.ace_layout')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>
                <div class="card-body">
                    <div class="row mt-3">
                        <div class="col-12">
                          <div class="card dcard">
                            <div class="card-body px-1 px-md-3">
                                <div class="d-flex justify-content-between flex-column flex-sm-row mb-3 px-2 px-sm-0">
                                  <h3 class="text-125 pl-1 mb-3 mb-sm-0 text-secondary-d4">
                                    {{ trans('cruds.user.title') }} {{ trans('global.list') }}
                                  </h3>
                                  <div class="pos-rel ml-sm-auto mr-sm-2 order-last order-sm-0">
                                    <i class="fa fa-search position-lc ml-25 text-primary-m1"></i>
                                    <input type="text" class="form-control w-100 pl-45 radius-1 brc-primary-m4" placeholder="Search ...">
                                  </div>

                                  <div class="mb-2 mb-sm-0">
                                    <a href="{{ route('admin.roles.create') }}" class="btn btn-blue px-3 d-block w-100 text-95 radius-round border-2 brc-black-tp10">
                                      <i class="fa fa-plus mr-1"></i>
                                       {{ trans('global.create') }}<span class="d-sm-none d-md-inline"> {{ trans('cruds.role.title_singular') }}</span>
                                    </a>
                                  </div>
                                </div>

                                <table id="simple-table" class="mb-0 table table-bordered-x brc-secondary-l3 text-dark-m2 radius-1 overflow-hidden">
                                    <thead class="text-dark-tp3 bgc-grey-l4 text-90 border-b-1 brc-transparent">
                                        <tr>
                                            <th class="text-center pr-0">
                                                <label class="py-0">
                                                <input type="checkbox" class="align-bottom mb-n1 border-2 text-dark-m3">
                                                </label>
                                            </th>
                                            <th>{{ trans('cruds.role.fields.id') }}</th>
                                            <th width="200px">{{ trans('cruds.role.fields.name') }}</th>
                                            <th width="200px">{{ trans('cruds.role.fields.slug') }}</th>
                                            <th>{{ trans('cruds.role.fields.description') }}</th>
                                            <th>{{ trans('cruds.role.fields.permission') }}</th>
                                            <th>{{ trans('global.action') }}</th>
                                        </tr>
                                    </thead>
                                    <tbody class="mt-1">
                                        @foreach ($roles as $key => $row)
                                            <tr class="bgc-h-yellow-l4 d-style">
                                                <td class="text-center pr-0 pos-rel">
                                                    <div class="position-tl h-100 ml-n1px border-l-4 brc-orange-m1 v-hover">
                                                        <!-- border shown on hover -->
                                                    </div>
                                                    <div class="position-tl h-100 ml-n1px border-l-4 brc-success-m1 v-active">
                                                        <!-- border shown when row is selected -->
                                                    </div>
                                                    <label>
                                                        <input type="checkbox" class="align-middle">
                                                    </label>
                                                </td>
                                                <td>
                                                <a href="#" class="text-blue-d1 text-600 text-95">{{ ++$key }}</a>
                                                </td>
                                                <td class="text-600 text-orange-d2">{{ $row->name }}</td>
                                                <td class="text-grey-d1">{{ $row->slug }}</td>
                                                <td class="text-600 text-orange-d2">
                                                    {{ $row->description }}
                                                </td>
                                                <td class="text-600 text-orange-d2">
                                                    @foreach ($row->permissions?? [] as $pmt)
                                                        <div class="badge badge-sm bgc-success-d1 text-white pb-1 px-25">
                                                            {{ $pmt->name  }}
                                                        </div>
                                                    @endforeach
                                                </td>
                                                <td>
                                                    <!-- action buttons -->
                                                    <div class="d-none d-lg-flex">
                                                        <a href="{{ route('admin.roles.edit',$row->id) }}" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-success">
                                                            <i class="fa fa-pencil-alt"></i>
                                                        </a>
                                                        <a href="javascript:deleteObject({{ $row->id }})" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger">
                                                            <i class="fa fa-trash-alt"></i>
                                                        </a>
                                                        <form id="frmDeletePost-{{ $row->id }}" style="display: none" action="{{ route('admin.roles.destroy', $row->id) }}" role="form" method="POST" enctype="multipart/form-data">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        <tr class="border-0 detail-row bgc-white">
                                            <td colspan="8" class="p-0 border-none brc-secondary-l2">
                                            <div class="table-detail collapse" id="table-detail-0">
                                                <div class="row">
                                                <div class="col-12 col-md-10 offset-md-1 p-4">
                                                    <div class="alert bgc-secondary-l4 text-dark-m2 border-none border-l-4 brc-primary-m1 radius-0 mb-0">
                                                    <h4 class="text-primary">
                                                        Row Details
                                                    </h4>
                                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo massa sed ipsum porttitor facilisis.
                                                    </div>
                                                </div>
                                                </div>
                                            </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                                <!-- table footer -->
                                <div class="d-flex pl-4 pr-3 pt-35 border-t-1 brc-secondary-l3 flex-column flex-sm-row mt-n1px">
                                  <div class="text-nowrap align-self-center align-self-sm-start">
                                    <span class="d-inline-block text-grey-d2">
                                      Showing 1 - 10 of 152
                                  </span>

                                    <select class="ml-3 ace-select no-border angle-down brc-h-blue-m3 w-auto pr-45 text-secondary-d3">
                                      <option value="10">Show 10</option>
                                      <option value="20">Show 20</option>
                                      <option value="50">Show 50</option>
                                    </select>
                                  </div>

                                  <div class="btn-group ml-sm-auto mt-3 mt-sm-0">
                                    <a href="#" class="btn btn-lighter-default btn-bgc-white btn-a-secondary radius-l-1 px-3 border-2">
                                      <i class="fa fa-caret-left mr-1"></i>
                                      Prev
                                    </a>
                                    <a href="#" class="btn btn-lighter-default btn-bgc-white btn-a-secondary radius-r-1 px-3 border-2 ml-n2px">
                                      Next
                                      <i class="fa fa-caret-right ml-1"></i>
                                    </a>
                                  </div>
                                </div>
                            </div><!-- /.card-body -->
                          </div><!-- /.card -->
                        </div><!-- /.col -->
                      </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        function deleteObject(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    document.getElementById('frmDeletePost-'+id).submit();
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            })
        }
    </script>
    <script type="text/javascript">
        jQuery(function($) {
            // highlight simple table row when selected
            function _highlight(row, checked) {
                if (checked) {
                    row.classList.add('active')
                    row.classList.add('bgc-success-l3')
                    row.classList.remove('bgc-h-default-l3')
                }
                else {
                    row.classList.remove('active')
                    row.classList.remove('bgc-success-l3')
                    row.classList.add('bgc-h-default-l3')
                }
            }

            $('#simple-table tbody tr').on('click', function(e)
            {
                var ret = false
                try {
                    // return if clicked on a .btn or .dropdown
                    ret = e.target.classList.contains('btn') || e.target.parentNode.classList.contains('btn')|| e.target.closest('.dropdown') != null
                } catch(err) {}
                if (ret) return
                var inp = this.querySelector('input')
                if(inp == null) return
                if(e.target.tagName != "INPUT") {
                    inp.checked = !inp.checked
                }
                _highlight(this, inp.checked)
            })

            $('#simple-table thead input').on('change', function()
            {
                var checked = this.checked
                $('#simple-table tbody input[type=checkbox]')
                .each(function() {
                    this.checked = checked
                    var row = $(this).closest('tr').get(0)
                    _highlight(row, checked)
                })
            })
        })
    </script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('layouts.ace_layout')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $role->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permissions:</strong>
            @if(!empty($rolePermissions))
                @foreach($rolePermissions as $v)
                    <label class="label label-success">{{ $v->name }},</label>
                @endforeach
            @endif
        </div>
    </div>
</div>
@endsection