routes/admin.php
<?php

    Route::group(['prefix' => env('ADMIN_ROUTE'),'namespace'=>'App\\Http\\Controllers\\Admin','as' =>'admin.','middleware'=>['web','auth']], function () {
        Route::get('/', function(){
            // return redirect()->route('admin.users.index');
            return redirect()->route('admin.dashboard.index');
        });
        // Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');

        // Route::get('/dashboard','DashboardController')->name('admin.dashboard');
        Route::resource('/dashboard','DashboardController');
        Route::resource('/users','UserController');
        Route::resource('/roles','RoleController');
        Route::resource('/permissions','PermissionController');
    });
?>

routes/front.php
<?php

use Laravel\Socialite\Facades\Socialite;
    Route::group(['prefix' => '','namespace'=>'App\\Http\\Controllers\\','as' =>'front.','middleware'=>['web']], function () {
        Route::view('/','homepage');
        Route::get('/business/register','BusinessController@register')->name('business.register');
        Route::post('/business/register','BusinessController@Saveregister')->name('business.register.save');
        Route::post('/business/register/check-username', 'BusinessController@postCheckUsername')->name('business.postCheckUsername');
        Route::post('/business/register/check-email', 'BusinessController@postCheckEmail')->name('business.postCheckEmail');
    });

?>

routes/user.php
<?php
Route::group(['prefix' => env('USER_ROUTE'),'namespace'=>'App\\Http\\Controllers\\Agent','as' =>'agent.','middleware'=>['web','auth']], function () {
    Route::get('/',function(){
        return "User Prefix";
    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Front\PropertyController;

Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});

Auth::routes();

Route::get('oauth/{provider}', 'App\Http\Controllers\Auth\LoginController@redirectToProvider');
Route::get('oauth/{provider}/callback','App\Http\Controllers\Auth\LoginController@handleProviderCallback');

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/properties', [PropertyController::class, 'index'])->name('front.properties');

app/Http/Controllers/Agent/AgentDashboardController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AgentDashboardController extends Controller
{
    public function index()
    {
        if(auth()->user()->hasRole('Agent')==1){
            // echo "Agent Page ";

            return view('agent.dashboard.dashboard');
        }
        // return view('home');
    }



    public function myads()
    {
        if(auth()->user()->hasRole('Agent')==1){
            // echo "Agent Page ";

            return view('agent.myads');
        }
        // return view('home');
    }


    public function myfavorite()
    {
        if(auth()->user()->hasRole('Agent')==1){
            // echo "Agent Page ";

            return view('agent.myfavorite');
        }
        // return view('home');
    }


}

resources/views/agent/includes/profile.blade.php
<div class="card">
    <div class="card-header">
        <h3 class="card-title">My Dashboard</h3>
    </div>
    <div class="card-body text-center item-user border-bottom">
        <div class="profile-pic">
            <div class="profile-pic-img">
                <span class="bg-success dots" data-toggle="tooltip" data-placement="top" title="online"></span>
                <img src="{{asset('public/images/faces/default.jpg')}}" class="brround" alt="user">
            </div>
            <a href="userprofile.html" class="text-dark"><h4 class="mt-3 mb-0 font-weight-semibold">{{Auth::user()->first_name}} {{Auth::user()->last_name}}</h4></a>
        </div>
    </div>
    <div class="item1-links  mb-0">
        <a href="{{route('agent.dashboard.index')}}" class="active d-flex border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-user"></i></span> Edit Profile
        </a>
        <a href="{{route('agent.myads')}}" class=" d-flex  border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-diamond"></i></span> My Ads
        </a>
        <a href="{{route('agent.myfavorite')}}" class=" d-flex border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-heart"></i></span> My Favorite
        </a>
        <a href="{{route('agent.myfavorite')}}" class="d-flex  border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-folder-alt"></i></span> Managed Ads
        </a>
        <a href="{{route('agent.myfavorite')}}" class=" d-flex  border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-credit-card"></i></span> Payments
        </a>
        <a href="{{route('agent.myfavorite')}}" class="d-flex  border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-basket"></i></span> Orders
        </a>
        <a href="{{route('agent.myfavorite')}}" class="d-flex border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-game-controller"></i></span> Safety Tips
        </a>
        <a href="{{route('agent.myfavorite')}}" class="d-flex border-bottom">
            <span class="icon1 mr-3"><i class="icon icon-settings"></i></span> Settings
        </a>


        <form method="POST" action="{{ route('logout') }}">
            @csrf
            <a class="d-flex" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                            this.closest('form').submit();">
                    <span class="icon1 mr-3"><i class="icon icon-power"></i></span>  {{trans('global.logout')}}
                </a>
        </form>
    </div>
</div>