routes/admin.php
<?php

    Route::group(['prefix' => env('ADMIN_ROUTE'),'namespace'=>'App\\Http\\Controllers\\Admin','as' =>'admin.','middleware'=>['web','auth']], function () {
        Route::get('/', function(){
            // return redirect()->route('admin.users.index');
            return redirect()->route('admin.dashboard.index');
        });
        // Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');

        // Route::get('/dashboard','DashboardController')->name('admin.dashboard');
        Route::resource('/dashboard','DashboardController');
        Route::resource('/users','UserController');
        Route::resource('/roles','RoleController');
        Route::resource('/permissions','PermissionController');
    });
?>

routes/front.php
<?php

use Laravel\Socialite\Facades\Socialite;
    Route::group(['prefix' => '','namespace'=>'App\\Http\\Controllers\\','as' =>'front.','middleware'=>['web']], function () {
        Route::view('/','homepage');
        Route::get('/business/register','BusinessController@register')->name('business.register');
        Route::post('/business/register','BusinessController@Saveregister')->name('business.register.save');
        Route::post('/business/register/check-username', 'BusinessController@postCheckUsername')->name('business.postCheckUsername');
        Route::post('/business/register/check-email', 'BusinessController@postCheckEmail')->name('business.postCheckEmail');
    });

?>

routes/user.php
<?php
Route::group(['prefix' => env('USER_ROUTE'),'namespace'=>'App\\Http\\Controllers\\Agent','as' =>'agent.','middleware'=>['web','auth']], function () {
    Route::get('/',function(){
        return "User Prefix";
    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Front\PropertyController;

Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});

Auth::routes();

Route::get('oauth/{provider}', 'App\Http\Controllers\Auth\LoginController@redirectToProvider');
Route::get('oauth/{provider}/callback','App\Http\Controllers\Auth\LoginController@handleProviderCallback');

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/properties', [PropertyController::class, 'index'])->name('front.properties');

resources/views/bussiness/en_lang.blade.php
<script>
    LANG = {
    'required': 'Required',
    'sure': 'Are you sure ?',
    'remove_product': 'Are you sure to remove the product?',
    'cancel_invoice':  'Are you sure to cancel the invoice?',
    'no_products': 'No products added',
    'paid_amount_is_less_than_payable': 'Paid amount is less than the payable amount. \nPlease press OK to submit the sale.',
    'paid_amount_is_more_than_payable': 'Paid amount is more than the payable amount. \nPlease check.',
    'confirm_delete_role': 'This role will be deleted.',
    'sku_already_exists': 'SKU already exists.',
    'ref_no_already_exists': 'Reference number already used.',
    'out_of_stock': 'Item out of stock',
    'delete_invoice_confirm': 'This setting will be deleted.',
    'add_name_as_new_customer': 'Add ":name" as new customer',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'last_7_days': 'Last 7 Days',
    'last_30_days': 'Last 30 Days',
    'this_month': 'This Month',
    'last_month': 'Last Month',
    'this_financial_year': 'Current financial year',
    'clear': 'Clear',
    'no_products_added': 'No Products added, add some products first',
    'some_error_in_input_field': 'Invalid inputs, Check & try again!!',
    'confirm_delete_expense_category': 'This category along with all expenses under this category will be deleted.',
    'confirm_delete_expense': 'This expense will be deleted.',
    'confirm_delete_payment': 'This payment will be deleted.',
    'confirm_delete_user': 'This user will be deleted',
    'confirm_delete_contact': 'This contact will be deleted',
    'confirm_delete_variation': "This variation along with all it's values will be deleted.",
    'confirm_tax_group': 'This tax group will be deleted.',
    'confirm_delete_category': 'This category along with all sub-categories under it will be deleted.',
    'confirm_delete_unit': 'This unit will be deleted.',
    'confirm_delete_tax_rate': 'This tax rate will be deleted.',
    'confirm_delete_brand': 'This brand will be deleted.',
    'confirm_delete_barcode': 'This barcode setting will be deleted.',
    'add_name_as_new_product': 'Add ":term" as new product',
    'no_products_found': 'No matching product found!',
    'cancel': 'Cancel',
    'ok': 'OK',
    'view_stock_details': 'View stock for each variation',
    'tour_step1_title': 'Application Tour',
    'tour_step1_content': "Let's go through the application in 7 quick steps..." ,
    'tour_step2_title': 'Step1: Shop Details',
    'tour_step2_content':'Here you can find your shop related information, Basic information, Product SKU, Discounts, Taxes & other settings.',
    'tour_step3_title': 'Step2: Adding Resources',
    'tour_step4_title': 'Step3: Suppliers & Customers',
    'tour_step4_content': 'All Suppliers & Customers for your shop.',
    'tour_step5_title': 'Step4: Manage Products',
    'tour_step6_title': 'Step5: Manage Purchases',
    'tour_step6_content': 'Manage Purchases and Payment for purchases.',
    'tour_step7_title': 'Step6: Manage Sales',
    'tour_step7_content': 'Sell -> POS, Use this screen while selling products or billing customer. Select Location, Add Products and Finalize it.',
    'tour_step8_title': 'Step7: Reports',
    'tour_step8_content':'View analytic reports for your shop. These reports help you get overall information about the performance of your business.',
    'label_no_product_error': 'Please, add atleast one product.',
    'confirm_delete_customer_group': 'This customer group will be deleted.',
    'prev': 'Prev',
    'next': 'Next',
    'end_tour': 'End tour',
    'inc_tax': 'Inc. Tax',
    'exc_tax': 'Exc. Tax',
    'file_browse_label': 'Browse..',
    'remove': 'Remove',
    'apply': 'Apply',
    'custom_range': 'Custom Range',
    'action': 'Action',
    'copy': 'Copy',
    'export_to_csv': 'Export to CSV',
    'export_to_excel': 'Export to Excel',
    'export_to_pdf': 'Export to PDF',
    'print': 'Print',
    'col_vis': 'Column visibility',
    'search': 'Search',
    'show': 'Show',
    'entries': 'entries',
    'table_emptyTable':'No data available in table',
    'table_info':'Showing _START_ to _END_ of _TOTAL_ entries',
    'table_infoEmpty':'Showing 0 to 0 of 0 entries',
    'table_loadingRecords':'Loading...',
    "table_processing":     "Processing...",
    "table_zeroRecords":    "No matching records found",
    "first":      "First",
    "last":       "Last",
    "previous":   "Previous",
    'contact_id_already_exists': 'Contact ID alredy exists',
    'register': 'Register',
    'specify_business_name': "Please specify your business name",
    'password_min_length': 'Password should be minimum 4 characters',
    'password_mismatch': 'Password Mismatched',
    'invalid_username': 'Invalid username or User already exist',
    'details': 'Details',
    'select_location': 'You must select location before selecting any products.',
    'location_id_already_exists': 'Location ID already exists',
    'add_name_as_new_supplier': 'Add ":name" as new supplier',
    'all': 'All',
    'filter_by_date': 'Filter by date',
    'form_will_get_reset': 'All added products will be removed.',
    'tour_step3_content_modified': 'Add Multiple Locations, Tax Rates, Invoice Settings for your shop.',
    'tour_step5_content_modified': 'Add Products - Simple or Variable Products <br> Create Variations for variable products <br> Create Units, Brands and Categories <br> Print labels',
    'pos_max_qty_error': 'Only :max_val :unit_name available',
    'lot_max_qty_error': 'Only :max_val :unit_name available in the selected Lot',
    'email_taken': 'This Email has already been taken.',
    'loading': 'Loading',
    'load_more': 'Load More',
    'mobile': 'Mobile',
    'something_went_wrong': 'Something went wrong',
    'max_rp_reached_error': 'Maximum :max_points :rp_name available',
    'min_order_total_error': 'Minimum order total should be :min_order to redeem :rp_name',
    'this_year': 'This Year',
    'last_year': 'Last Year',
    'last_financial_year': 'Last financial year',
    'this_month_last_year': 'This month last year',
    'edit' : 'Edit',
    'delete' : 'Delete',
    'view' : 'View',
    'customer' : 'Customer',
    'this_card_has_a_due_date' : 'This card has a due date',
    'this_card_has_a_end_date' : 'This card has a end date',
    'this_card_has_a_description' : 'This card has a description',
    'this_card_has_comments' : 'This card has comments',
    'more' : ' more',
    'lead' : 'Lead',
    'project' : 'Project',
    'overview' : 'Overview',
    'activities' : 'Activities',
    'task' : 'Task',
    'time_logs' : 'Time Logs',
    'documents_and_notes' : 'Documents & Note',
    'invoices': 'Invoices',
    'settings' : 'Settings',
    'advance_payment_cannot_be_more_than_once': 'Advance payment cannot be selected more than once',
    'not_connected_to_a_network': "You're not connected to a Network",
};

</script>

resources/views/bussiness/login.blade.php
<script>
    $(document).ready(function() {
    $('[data-toggle="tooltip"]').tooltip();
    // registration form steps start
    if ($('#business_register_form').length) {
        var form = $('#business_register_form').show();
        form.steps({
            headerTag: 'h3',
            bodyTag: 'fieldset',
            transitionEffect: 'slideLeft',
            labels: {
                finish: LANG.register,
                next: LANG.next,
                previous: LANG.previous,
            },
            onStepChanging: function(event, currentIndex, newIndex) {
                // Allways allow previous action even if the current form is not valid!
                if (currentIndex > newIndex) {
                    return true;
                }
                // Needed in some cases if the user went back (clean up)
                if (currentIndex < newIndex) {
                    // To remove error styles
                    form.find('.body:eq(' + newIndex + ') label.error').remove();
                    form.find('.body:eq(' + newIndex + ') .error').removeClass('error');
                }
                // form.validate().settings.ignore = ':disabled,:hidden';
                // return form.valid();
            },
            onFinishing: function(event, currentIndex) {
                // form.validate().settings.ignore = ':disabled';
                // return form.valid();
            },
            onFinished: function(event, currentIndex) {
                form.submit();
            },
        });
    }
    // registration form steps end

    //Date picker
    // $('.start-date-picker').datepicker({
    //     autoclose: true,
    //     endDate: 'today',
    // });

    // $('form#business_register_form').validate({
    //     errorPlacement: function(error, element) {
    //         if (element.parent('.input-group').length) {
    //             error.insertAfter(element.parent());
    //         } else if (element.hasClass('input-icheck') && element.parent().hasClass('icheckbox_square-blue')) {
    //             error.insertAfter(element.parent().parent().parent());
    //         } else {
    //             error.insertAfter(element);
    //         }
    //     },
    //     rules: {
    //         name: 'required',
    //         email: {
    //             email: true,
    //             remote: {
    //                 url: '/business/register/check-email',
    //                 type: 'post',
    //                 data: {
    //                     email: function() {
    //                         return $('#email').val();
    //                     },
    //                 },
    //             },
    //         },
    //         password: {
    //             required: true,
    //             minlength: 5,
    //         },
    //         confirm_password: {
    //             equalTo: '#password',
    //         },
    //         username: {
    //             required: true,
    //             minlength: 4,
    //             remote: {
    //                 url: '/business/register/check-username',
    //                 type: 'post',
    //                 data: {
    //                     username: function() {
    //                         return $('#username').val();
    //                     },
    //                 },
    //             },
    //         },
    //         website: {
    //             url: true,
    //         },
    //     },
    //     messages: {
    //         name: LANG.specify_business_name,
    //         password: {
    //             minlength: LANG.password_min_length,
    //         },
    //         confirm_password: {
    //             equalTo: LANG.password_mismatch,
    //         },
    //         username: {
    //             remote: LANG.invalid_username,
    //         },
    //         email: {
    //             remote: LANG.email_taken,
    //         },
    //     },
    // });

    // $('#business_logo').fileinput({
    //     showUpload: false,
    //     showPreview: false,
    //     browseLabel: LANG.file_browse_label,
    //     removeLabel: LANG.remove,
    // });
});

</script>

resources/views/bussiness/register.blade.php
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <base href="{{asset('/')}}" />
    <title>@yield('pagetitle','Reallist Home Page')</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- include common vendor stylesheets & fontawesome -->
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/node_modules/bootstrap/dist/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/node_modules/@fortawesome/fontawesome-free/css/fontawesome.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/node_modules/@fortawesome/fontawesome-free/css/regular.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/node_modules/@fortawesome/fontawesome-free/css/brands.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/node_modules/@fortawesome/fontawesome-free/css/solid.css')}}">
    <!-- include fonts -->
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/select2/dist/css/select2.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/tiny-date-picker/tiny-date-picker.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/tiny-date-picker/date-range-picker.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css">
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/dist/css/ace-font.css')}}">
    <!-- ace.css -->
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/dist/css/ace.css')}}">
    <!-- favicon -->
    <link rel="icon" type="image/png" href="{{asset('public/backend/favicon.png')}}" />
    <link rel="stylesheet" type="text/css" href="{{asset('public/backend/dist/css/ace-themes.css')}}">
    <link rel="stylesheet" href="{{ asset('public/front') }}/steps/css/main.css">
    <link rel="stylesheet" href="{{ asset('public/front') }}/steps/css/jquery.steps.css">
    <style>
        body{
            font-family: 'Hanuman', 'serif' !important;
        }
        .wizard > .content {
            min-height: 41rem;
        }
        .wizard, .tabcontrol {
            z-index: -1;
        }
    </style>
  </head>

<body>
    @include('frontend.layouts.top_nav')

    <div class="container-fluid bgc-white">


        <div class="row">
            <div class="col-md-4 pt-12">
                <img style="vertical-align: middle;
                display: inline-block;
                position: relative;max-width: 100%;padding-top: 100px !important;" src="{{asset('public/images/register.png')}}" alt="">
            </div>
            <div class="col-md-8 pt-15">
                <form id="business_register_form" action="{{ route('front.business.register.save') }}" method="POST" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    @include('bussiness.form')
                </form>
            </div>
        </div>
    </div>


    @include('layouts.partials.front_footer')


    <!-- jQuery library -->
    <script src="{{asset('public/backend/node_modules/jquery/dist/jquery.js')}}"></script>
    <script src="{{asset('public/backend/node_modules/popper.js/dist/umd/popper.js')}}"></script>
    <script src="{{asset('public/backend/node_modules/bootstrap/dist/js/bootstrap.js')}}"></script>
    <script src="{{ asset('public/backend') }}/node_modules/select2/dist/js/select2.js"></script>
    @include('sweetalert::alert')
    <script src="{{ asset('public/backend') }}/node_modules/tiny-date-picker/dist/date-range-picker.js"></script>
    <script src="{{ asset('public/backend') }}/node_modules/moment/moment.js"></script>
    <script src="{{ asset('public/backend') }}/node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js"></script>
    <script src="{{ asset('public/front') }}/steps/build/jquery.steps.js"></script>
    <script src="{{ asset('public/backend') }}/dist/js/ace.js"></script>
    @include('bussiness.en_lang')
    {{-- @include('bussiness.login') --}}
    <script>
        $(document).ready(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            if ($('#business_register_form').length) {
                var form = $('#business_register_form').show();
                form.steps({
                    headerTag: 'h3',
                    bodyTag: 'fieldset',
                    transitionEffect: 'slideLeft',
                    labels: {
                        finish: 'Resister',
                        next: 'Next',
                        previous: 'Previous',
                    },
                    onStepChanging: function(event, currentIndex, newIndex) {
                       // Allways allow previous action even if the current form is not valid!
                        if (currentIndex > newIndex) {
                            return true;
                        }
                        //Needed in some cases if the user went back (clean up)
                        if (currentIndex < newIndex) {
                            // To remove error styles
                            form.find('.body:eq(' + newIndex + ') label.error').remove();
                            form.find('.body:eq(' + newIndex + ') .error').removeClass('error');
                        }
                        form.validate().settings.ignore = ':disabled,:hidden';
                        return form.valid();
                    },
                    onFinishing: function(event, currentIndex) {
                        form.validate().settings.ignore = ':disabled';
                        return form.valid();
                    },
                    onFinished: function(event, currentIndex) {
                        // alert('submit');
                        form.submit();
                    },
                })
            }
            // var TinyDatePicker = DateRangePicker.TinyDatePicker;
            // TinyDatePicker('#currency_id', {
            //     mode: 'dp-below',
            // });
            $('#start_date').datetimepicker({
                format: 'DD/MM/YYYY',
                icons: {
                    time: 'far fa-clock text-green-d1 text-120',
                    date: 'far fa-calendar text-blue-d1 text-120',
                    up: 'fa fa-chevron-up text-secondary',
                    down: 'fa fa-chevron-down text-secondary',
                    previous: 'fa fa-chevron-left text-secondary',
                    next: 'fa fa-chevron-right text-secondary',
                    today: 'far fa-calendar-check text-purple-d1 text-120',
                    clear: 'fa fa-trash-alt text-orange-d2 text-120',
                    close: 'fa fa-times text-danger text-120'
                },
                // sideBySide: true,
                toolbarPlacement: "top",
                allowInputToggle: true,
                // showClose: true,
                // showClear: true,
                showTodayButton: true,
                //"format": "HH:mm:ss"
            });
            $('#start_date').on('dp.show', function() {
                $(this).find('.collapse.in').addClass('show')
                $(this).find('.table-condensed').addClass('table table-borderless')
                $(this).find('[data-action][title]').tooltip() // enable tooltip
            });
            $('#business_logo').aceFileInput({
                // btnChooseClass: 'bgc-grey-l2 pt-15 px-2 my-1px mr-1px',
                // btnChooseText: 'SELECT FILE',
                // placeholderText: 'NO FILE YET',
                // placeholderIcon: '<i class="fa fa-upload bgc-warning-m1 text-white w-4 py-2 text-center"></i>'
            });
            // select2
            $('.select2').select2({
                allowClear: true,
                dropdownParent: $('#select2-parent'),
            });

            $('#business_register_form').validate({
                errorPlacement: function(error, element) {
                    if (element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else if (element.hasClass('input-icheck') && element.parent().hasClass('icheckbox_square-blue')) {
                        error.insertAfter(element.parent().parent().parent());
                    } else {
                        error.insertAfter(element);
                    }
                },
                rules: {
                    name: 'required',
                    email: {
                        email: true,
                        remote: {
                            url: "{{ route('front.business.postCheckEmail') }}",
                            type: 'post',
                            data: {
                                email: function() {
                                    return $('#email').val();
                                },
                            },
                        },
                    },
                    password: {
                        required: true,
                        minlength: 5,
                    },
                    confirm_password: {
                        equalTo: '#password',
                    },
                    username: {
                        required: true,
                        minlength: 4,
                        remote: {
                            url: "{{ route('front.business.postCheckUsername') }}",
                            type: 'post',
                            data: {
                                username: function() {
                                    return $('#username').val();
                                },
                            },
                        },
                    },
                    website: {
                        url: true,
                    },
                },
                messages: {
                    name: LANG.specify_business_name,
                    password: {
                        minlength: LANG.password_min_length,
                    },
                    confirm_password: {
                        equalTo: LANG.password_mismatch,
                    },
                    username: {
                        remote: LANG.invalid_username,
                    },
                    email: {
                        remote: LANG.email_taken,
                    },
                },
            });
        });

    </script>
</body>
</html>